/* tslint:disable */
/* eslint-disable */
/**
 * Belajar OpenAPI
 * Untuk belajar membuat RESTfull API
 *
 * OpenAPI spec version: 1.0
 * Contact: yogajprasutiyo@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TodoList } from './todo-list';
/**
 * 
 * @export
 * @interface ArrayTodoList
 */
export interface ArrayTodoList extends Array<TodoList> {
}
