/* tslint:disable */
/* eslint-disable */
/**
 * Belajar OpenAPI
 * Untuk belajar membuat RESTfull API
 *
 * OpenAPI spec version: 1.0
 * Contact: yogajprasutiyo@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TodoList
 */
export interface TodoList {
    /**
     * 
     * @type {string}
     * @memberof TodoList
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TodoList
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof TodoList
     */
    priority?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof TodoList
     */
    tags?: Array<string>;
}
